import { StyleSheet } from 'react-native';
import { spacing, type ThemeColors } from '@/shared/theme';

export const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    header: {
      paddingTop: 12,
      paddingBottom: spacing.sm,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    iconBtn: {
      width: 36,
      height: 36,
      borderRadius: 12,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerLabel: {
      fontSize: 11,
      color: c.textSecondary,
      letterSpacing: 1.6,
      fontWeight: '600',
    },

    hero: {
      alignItems: 'center',
      paddingTop: 20,
      paddingBottom: 22,
    },
    heroAvatarWrap: {
      position: 'relative',
    },
    heroCameraBtn: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.primary,
      borderWidth: 3,
      borderColor: c.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroNameWrap: {
      marginTop: 16,
      alignItems: 'center',
    },
    heroMeta: {
      marginTop: 6,
      fontSize: 11,
      color: c.textSecondary,
      letterSpacing: 1,
      fontWeight: '600',
    },

    sectionLabel: {
      paddingTop: 18,
      paddingBottom: 8,
      paddingHorizontal: 4,
      fontSize: 10.5,
      color: c.faint,
      letterSpacing: 1.6,
      fontWeight: '600',
    },

    card: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: 14,
      overflow: 'hidden',
    },

    divider: {
      height: 1,
      backgroundColor: c.line,
      marginLeft: 56,
    },

    row: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    rowIconBubble: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowTitle: {
      flex: 1,
      fontSize: 13.5,
      fontWeight: '600',
      color: c.text,
      letterSpacing: -0.2,
    },
    rowValue: {
      fontSize: 12,
      color: c.textSecondary,
    },
    rowValueMono: {
      fontSize: 12,
      color: c.textSecondary,
      letterSpacing: 0.6,
      fontVariant: ['tabular-nums'],
    },

    toggleRow: {
      paddingHorizontal: 14,
      paddingVertical: 11,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    toggleTitle: {
      fontSize: 13.5,
      fontWeight: '600',
      color: c.text,
      letterSpacing: -0.2,
    },
    toggleSub: {
      fontSize: 11,
      color: c.textSecondary,
      marginTop: 1,
    },

    segmentRow: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    segmentTrack: {
      flexDirection: 'row',
      backgroundColor: c.surface2,
      borderRadius: 9,
      padding: 2,
    },
    segmentBtn: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 7,
    },
    segmentBtnActive: {
      backgroundColor: c.text,
    },
    segmentLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      letterSpacing: 0.4,
      color: c.textSecondary,
    },
    segmentLabelActive: {
      color: c.background,
    },

    radiusHeader: {
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    radiusBadge: {
      minWidth: 72,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: c.primarySoft,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      alignItems: 'center',
    },
    radiusBadgeLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: c.primary,
      letterSpacing: 0.4,
      fontVariant: ['tabular-nums'],
    },
    radiusTrackWrap: {
      paddingHorizontal: 14,
      paddingBottom: 8,
    },
    radiusTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: c.surface2,
      overflow: 'hidden',
    },
    radiusFill: {
      height: 6,
      borderRadius: 3,
    },
    radiusThumb: {
      position: 'absolute',
      top: -7,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: c.text,
      borderWidth: 3,
      borderColor: c.background,
    },
    radiusTicks: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 16,
    },
    radiusTickBtn: {
      paddingHorizontal: 6,
      paddingVertical: 4,
    },
    radiusTickLabel: {
      fontSize: 10,
      color: c.faint,
      letterSpacing: 0.6,
      fontWeight: '700',
    },
    radiusTickLabelActive: {
      color: c.primary,
    },

    dmList: {
      gap: 6,
    },
    dmOption: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: c.line,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    dmOptionActive: {
      borderColor: c.primary,
      backgroundColor: c.primarySoft08,
    },
    dmOptionWithExceptions: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderBottomColor: c.anchorTileBorder,
    },
    dmIconBubble: {
      width: 26,
      height: 26,
      borderRadius: 7,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surface2,
    },
    dmIconBubbleActive: {
      backgroundColor: c.primary,
    },
    dmOptionTextWrap: {
      flex: 1,
    },
    dmOptionLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: c.text,
    },
    dmOptionSub: {
      fontSize: 10.5,
      color: c.textSecondary,
      marginTop: 1,
    },
    dmExceptionsBlock: {
      backgroundColor: c.primarySoft08,
      borderWidth: 1,
      borderTopWidth: 0,
      borderColor: c.primary,
      borderBottomLeftRadius: 11,
      borderBottomRightRadius: 11,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 12,
    },
    dmExceptionsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    dmExceptionsHeaderLabel: {
      fontSize: 10.5,
      color: c.textSecondary,
      letterSpacing: 1.4,
      fontWeight: '600',
    },
    dmExceptionsHeaderCount: {
      fontSize: 10.5,
      color: c.faint,
      letterSpacing: 0.6,
      fontWeight: '600',
    },
    dmChipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    dmChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingLeft: 10,
      paddingRight: 5,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
    },
    dmChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: c.text,
    },
    dmChipRemoveBtn: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: c.surface2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dmAddBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.primary,
      borderStyle: 'dashed',
    },
    dmAddBtnText: {
      fontSize: 12,
      fontWeight: '600',
      color: c.primary,
    },
    dmLoadMoreBtn: {
      marginTop: 10,
      alignSelf: 'flex-start',
      minHeight: 30,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dmExceptionState: {
      minHeight: 42,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dmPickerDrawer: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: c.anchorTileBorder,
      borderStyle: 'dashed',
    },
    dmPickerEmpty: {
      fontSize: 11.5,
      color: c.faint,
      paddingVertical: 8,
    },
    dmPickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 8,
      paddingVertical: 7,
      borderRadius: 8,
    },
    dmPickerAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dmPickerAvatarLetter: {
      color: c.white,
      fontWeight: '700',
      fontSize: 11,
    },
    dmPickerName: {
      fontSize: 12.5,
      fontWeight: '600',
      color: c.text,
    },
    dmPickerHint: {
      fontSize: 9.5,
      color: c.faint,
      letterSpacing: 0.5,
      marginTop: 1,
      fontWeight: '600',
    },

    outlinedBtn: {
      marginTop: 14,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.line,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    outlinedBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: c.text,
    },
    dangerBtn: {
      marginTop: 8,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.dangerBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dangerBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: c.error,
    },

    nameInput: {
      minWidth: 160,
      paddingVertical: 2,
      fontSize: 24,
      fontWeight: '700',
      color: c.text,
      letterSpacing: -0.6,
      borderBottomWidth: 2,
      borderBottomColor: c.primary,
      textAlign: 'center',
    },
    nameViewWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    nameViewText: {
      fontSize: 24,
      fontWeight: '700',
      color: c.text,
      letterSpacing: -0.6,
    },
  });
